# Generated by Django 3.1.3 on 2020-11-28 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metallics_api', '0003_auto_20201128_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemicalconcentration',
            name='element_id',
        ),
        migrations.AddField(
            model_name='chemicalconcentration',
            name='element_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='metallics_api.chemicalelement'),
            preserve_default=False,
        ),
    ]
